### PR TITLE
Update CREATE_BOT.md images

### LINKED ISSUE #2: Docs: CREATE_BOT.md Image Not Displaying
### Current Image Display:

Screenshot 2023-10-13 at 5:51:37 PM

### Requested Changes:

Please replace the existing images with the following [screenshots](https://drive.google.com/drive/u/1/folders/1thJwjg6sdFfsGlLdTnarU8Bo0BP-JmEc) in [CREATE_BOT.md](https://github.com/0xVikasRushi/OpenIssueMonitor/blob/main/CREATE_BOT.md). Additionally, adjust the size of the new screenshots as needed for proper display.

### PR DESCRIPTION
**Pull request by AmosBlack**
Fixed broken images from gdrive link.
Resolves #2

### CODE REVIEW

**Comment by AmosBlack** [comment]
image
Screenshots of working  .md file

**Comment by 0xVikasRushi** [comment]
LGTM!

**Comment by AmosBlack** [comment]
If you feel like I fixed something worthwhile, please add the hacktoberfest-accepted and hacktoberfest labels to this PR since my dumb self forgot to link it to the original issue.

**Comment by AmosBlack** [comment]
If I did something worthwhile, please assign the required hacktoberfest-accepted label to the PR. Thankyou !

**Pull request merged**
